### ISSUE TITLE
Logo Design 

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/bb8_moving_squareROS#1]
Hi, @eduardorasgado  I'd like to collaborate on this open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by eduardorasgado** [comment]
Thanks for your interest @zuurw. This is most like an experimental work. I think this project does not deserve a logo. :x:

**Comment by zuurw** [comment]
Ok no problem!
